#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

if [ ! -e "bin/codegen-assembly-0.1.jar" ]; then
  sbt assembly || die "SBT build failed, maybe SBT needs to be installed?"
  cp target/scala-2.11/codegen-assembly-0.1.jar bin/codegen-assembly-0.1.jar
fi

java -jar bin/codegen-assembly-0.1.jar $@
